name: navidrome

services:
  navidrome-rw:
    image: regyl/navidrome-rw:latest
    container_name: navidrome-rw
    ports:
      - "12080:12080"
    environment:
      - YM_NAVIDROME_DATA=/navidrome/navidromerw/data
      - NAVIDROME_FOLDER=/navidrome/transfer
      - YTDLP_DOWNLOAD_DIR=/navidrome/navidromerw/tmp/ytdlp
      - SLSK_DOWNLOAD_DIR=/navidrome/navidromerw/tmp/slskd
      - SLSK_USERNAME=RandomUserName # change this
      - SLSK_PASSWORD=RandomPassword # change this
      - YANDEX_MUSIC_TOKEN=MegaToken # change this
      - YANDEX_MUSIC_PERIOD_BETWEEN_REQUESTS=3
    volumes:
      - /home/navidrome:/navidrome
    restart: unless-stopped
